/**
 * OOPSBannerApp
 *
 * UC2: Print "OOPS" as a 7-line ASCII banner using
 * individual print statements (no loops).
 *
 * @author YourName
 * @version 2.0
 */
public class OOPSBannerApp {

    /**
     * Main method - Entry point
     * @param args command line arguments
     */
    public static void main(String[] args) {

        System.out.println(" *****   *****   *****   ***** ");
        System.out.println("*     * *     * *     * *     *");
        System.out.println("*     * *     * *     * *     *");
        System.out.println("*     * *     * *****   ***** ");
        System.out.println("*     * *     * *       *   * ");
        System.out.println("*     * *     * *       *    *");
        System.out.println(" *****   *****   *       *     *");
    }
}